name: CI

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [notification-push-main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Set up Erg
        uses: erg-lang/setup-erg@v2.1
      - name: Run script
        run: |
          erg --version
          curl -L https://github.com/erg-lang/the-erg-book/raw/main/replace_links.er | erg --dump-as-pyc
          curl -L https://github.com/mtshiba/ergup/raw/main/ergup.er | erg --dump-as-pyc
