name: CI

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [notification-push-main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Erg & Test
        run: |
          git clone https://github.com/erg-lang/erg
          cd erg
          rustup update stable
          cargo install --path . --debug --features large_thread
          echo "ERG_PATH=/home/runner/.erg" >> $GITHUB_ENV
      - name: Run script
        run: |
          erg --version
          erg --dump-as-pyc dismore.er
          curl -LO https://github.com/erg-lang/erg/raw/main/doc/scripts/mylib.py
          curl -LO https://github.com/erg-lang/erg/raw/main/doc/scripts/mylib.d.er
          curl -L https://github.com/erg-lang/erg/raw/main/doc/scripts/sync_to_translation_status.er | erg --dump-as-pyc

          curl -L https://github.com/erg-lang/the-erg-book/raw/main/replace_links.er | erg --dump-as-pyc
          curl -LO https://github.com/mtshiba/ergup/raw/main/ergup.er
          erg --dump-as-pyc ergup.er
          echo y | python3 ergup.pyc
      - name: Run ergup.py
        if: ${{ matrix.python-version == '3.11' || matrix.python-version == '3.10' }}
        run: |
          erg trans ergup.er
          echo y | python3 ergup.py
  poise:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: erg-lang/poise
          ref: main
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Erg & Test
        run: |
          git clone https://github.com/erg-lang/erg
          cd erg
          rustup update stable
          cargo install --path . --debug --features large_thread
          echo "ERG_PATH=/home/runner/.erg" >> $GITHUB_ENV
      - name: Set up Poise & Run
        run: |
          erg src/main.er
