name: CI

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [notification-push-main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Erg & Test
        run: |
          git clone https://github.com/erg-lang/erg
          cd erg
          cargo install --path . --debug
      - name: Run script
        run: |
          erg --version
          curl -LO https://github.com/erg-lang/erg/raw/main/doc/scripts/mylib.py
          curl -LO https://github.com/erg-lang/erg/raw/main/doc/scripts/mylib.d.er
          curl -L https://github.com/erg-lang/erg/raw/main/doc/scripts/sync_to_translation_status.er | erg --dump-as-pyc

          curl -L https://github.com/erg-lang/the-erg-book/raw/main/replace_links.er | erg --dump-as-pyc
          curl -L https://github.com/mtshiba/ergup/raw/main/ergup.er | erg --dump-as-pyc
          erg --dump-as-pyc dismore.er
